- name: make dir and file
  hosts: ansi-node2
  gather_facts: no
  vars:
    list1:
    - a
    - b
    - c
    list2:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  tasks:
  - file:
      state: directory
      path: /testdir

  - file:
      state: touch
      path: "/testdir/file{{ item[0] }}{{ item[1] }}"
    loop: "{{ list1 | product(list2) | list }}"
    
#/testdir/ 안에 아래 파일 만들기
#filea(1-10)
#fileb(1-10)
#filec(1-10)
#filed(1-10)
